services:
  - type: web
    name: halfcivilian-bot
    env: python
    repo: https://github.com/yourusername/your-private-repo
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: TOKEN
        value: your_bot_token_here
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
